name: Build and Test
on:
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        description: Build profile to use
        options:
          - development
          - preview
          - production
jobs:
  build-and-test:
    strategy:
      fail-fast: true
      matrix:
        include:
          - platform: "ios"
            os: "macos-latest"
          - platform: "android"
            os: "ubuntu-latest"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit == 'false' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        run: npm install

      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Setup EAS local builds
        run: npm i -g eas-cli-local-build-plugin

      - name: Test
        run: npm run test

      - name: Build
        run: |
          eas build --local \
            --non-interactive \
            --output=./out \
            --platform=${{ matrix.platform }} \
            --profile=${{ github.event.inputs.profile }}

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: your-app-name-${{ matrix.platform }}
          path: out
